apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../

images:
  - name: ghcr.io/deep95y/notes-management-backend
    newName: notes-backend
    newTag: local
  - name: ghcr.io/deep95y/notes-management-frontend
    newName: notes-frontend
    newTag: local
